
resources:
  - name: git-repo
    type: git
    source:
      uri: https://github.com/vc4017/concourse-java-maven-test-prj.git
      branch: master
  - name: time
    type: time
    source:
      interval: 60s


jobs:
  - name: maven-package
    plan:
    - aggregate:
      - get: git-repo
        trigger: true
      - get: time
    - task: maven-package
      privileged: true
      file: git-repo/pipeline/maven-package.yml
    - task: rename-file
      file: git-repo/pipeline/rename-file.yml

#   - name: rename file
#     plan:
#     - aggregate:
#       - get: jar-file
#         trigger: true
#         passed: [maven-package]
#       - get: time
#     - task: rename-file
#       file: git-repo/pipeline/rename-file.yml